### ISSUE TITLE
On the calculation of standard diagnostics

### ISSUE THREAD

**Issue by IvanUkhov** [stan-dev/pystan#316] opened 2021-07-22 06:09 UTC
This is related to #150 but slightly more general. In versions prior to version 3, it was possible to calculate the following five standard diagnostics, as recommended by Michael Betancourt:

https://github.com/betanalpha/jupyter_case_studies/blob/master/pystan_workflow/stan_utility.py

In the current output, I see `divergent__`, `treedepth__`, and `energy__`. This probably means that the first three can be computed even in version 3. However, with energy, it is not as clear, at the code seems to assume some particular ordering of the energy values; mostly likely, each chain has to be processed separately, which is what the API does not allow. The remaining two, the effective number of samples and R hat, require Stan’s summary, which is not provided.

I am curious if the above is a fair summary of the current situation. In addition, if anybody has insight into what the underlying C++ code is doing, are any of these checks performed automatically with warnings if appropriate?

**Comment by riddell-stan** [comment] 2021-08-13 14:50
If there's support for calculating these values in Stan C++, there's no obstacle to writing code to make these values available via pystan.

IIRC, there's only support for calculating rhat/ess in Stan C++ currently (see #150 for work on this).

I'm going to close this because we're using the issue tracker for bugs and confirmed features. Please feel free to post this query on the Stan forums.

**Closed by riddell-stan** 2021-08-13 14:50 UTC
