### ISSUE TITLE
Initialization with user-specified value in sampling method

### ISSUE THREAD

**Issue by sheqi** [stan-dev/pystan#352] opened 2017-06-19 18:35 UTC
#### Summary:
Hi, I have encountered the initialization problem with user-specified parameter. Thanks for the help in advance !

#### Description:
I compile the model once to use the model across different scripts. I load the compiled file and use sampling method with user-specified parameters, the parameters estimated are always the same as the initial value. 

The following codes can be run directly.

#### Reproducible Steps:
# 1. the model to compile

```
import pickle
from pystan import StanModel

model = """
data {
   int<lower=1> N; 
   matrix[N,N] W; 
   int<lower=1> B;
}
parameters {
   matrix[N,2] l;
   real<lower=0> sigma;
   real<lower=0> eta;
   real<lower=0> rho;
}
model {
   sigma ~ inv_gamma(1,1);
   for (i in 1:N)
        for (j in 1:2)
            l[i,j] ~ normal(0, sigma);
   for (i in 1:N)
        for (j in 1:N)
            W[i,j] ~ normal(0, eta*exp(-rho*squared_distance(l[i,:],l[j,:])/2)); 
}
"""
sm = StanModel(model_code=model)

with open('model.pkl', 'wb') as f:
    pickle.dump(sm, f)
```

# 2. in another script, I try to estimate the parameter 

```
import pickle
import numpy as np
import numpy.random as npr

dim = 2
N = 20
r = 1 + np.arange(N) // (N/2.)
th = np.linspace(0, 4 * np.pi, N, endpoint=False)
x = r * np.cos(th)
y = r * np.sin(th)
L = np.hstack((x[:, None], y[:, None]))

W = np.zeros((N, N))

D = ((L[:, None, :] - L[None, :, :]) ** 2).sum(2)
sig = np.exp(-D/2)
Sig = np.tile(sig[:, :, None, None], (1, 1, 1, 1))

Mu = np.zeros((N,N,1))

# Generate data from true L
for n in range(N):
    for m in range(N):
        W[n, m] = npr.multivariate_normal(Mu[n, m], Sig[n, m])

aa = 1.0
bb = 1.0
cc = 1.0

sm = pickle.load(open('model.pkl', 'rb'))

new_data = dict(N=N, W=W, B=dim)

L_init = np.random.randn(N, dim)
fit = sm.sampling(data=new_data, iter=100, warmup=0, chains=1, init=[dict(l=L_init, sigma=aa, eta=bb, rho=cc)], control=dict(stepsize=0.05))

samples = fit.extract(permuted=True)
aa = np.mean(samples['sigma'])
bb = np.mean(samples['eta'])
cc = np.mean(samples['rho'])
L = np.mean(samples['l'], 0)
```

#### Current Output:
After fitting the model with the initial value we specified, the output "aa", "bb", "cc", "L" keeps unchanged.

#### Expected Output:
We should get the optimized value of parameters

#### PyStan Version:
2.15.0.1

#### Python Version:
Python 3.6

#### Operating System:
Mac OS 10.12.4

**Comment by bob-carpenter** [comment] 2017-06-19 19:33
@sheqi:  This is probably not a bug in PyStan---you're more likely to get modeling help on our mailing list at http://discourse.mc-stan.org

The problem here is likely to be setting `warmup=0`.  Stan needs to adapt to the posterior before it can move unless you set  a very low initial step size. 

I think PyStan 2.15, like our other interfaces, is supressing error messages when there are exceptions.  This will be fixed in the 2.16 release we should get out soon.

**Comment by sheqi** [comment] 2017-06-19 19:58
@bob-carpenter, thanks for the advice, I have tried it and it is the problem of warmup=0 setup. 
I set it to be 0 because I want to use each sample of estimated parameter in my gibbs sampler, and in this process, I need to initialize the parameters in stan model from last stan's output (same stan model). Is there any way to do it ? Thanks !

**Comment by bob-carpenter** [comment] 2017-06-20 16:33
Not yet.  Also, we have no idea what changing the continuous density (in effect what happens when you Gibbs sample some other parameters) will do to warmup (mass matrix and step size).  So rather than running one iteration of HMC, you can warmup and then step a few times each iteration---you still get a valid sampler if you do that.

In 2.17 (the release after next), we should have a way built in to warmup and save the mass matrix and step size to allow restarts.

**Comment by sheqi** [comment] 2017-06-20 20:09
@bob-carpenter Thanks ！I would like to try using the sample after stepping a few times each iteration.

**Comment by ariddell** [comment] 2017-09-15 11:34
If there's an issue remaining here (e.g., save/loading mass matrix or similar) let's open up a fresh issue with a different title.

**Closed by ariddell** 2017-09-15 11:34 UTC
