### ISSUE TITLE
cov_exp_quad signature error

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#271] opened 2016-11-16 20:05 UTC
Using PyStan 2.12.0.0 the following model does not compile on PyStan but compiles fine on cmdstan:

```stan
data {
	real rx1[5];
}
model {
	matrix[5,5] a;

	a = cov_exp_quad(rx1, 1, 1);
}
```

The (C++) compiler error is:

```
error: no matching function for call to ‘cov_exp_quad(const std::vector<double>&, int, int)’
                 stan::math::assign(a, cov_exp_quad(rx1,1,1));
```

I'm assuming something is not being included correctly.

Thanks to Nathan Sanders for the bug report and example.

**Comment by syclik** [comment] 2016-11-16 20:08
Hmmm. What compiler? Does it complies with 1.0 instead of 1?

**Comment by ariddell** [comment] 2016-11-16 20:11
Looks like the relevant include is missing from the stan_math that shipped with PyStan 2.12.0. There's no include line in ``stan/math/rev/mat.hpp``.

**Comment by ariddell** [comment] 2016-11-16 20:17
This is happening under clang and gcc. Maybe it's something else. This is another error:

```
pystan/stan/src/stan/model/util.hpp:186:58: error: cannot convert ‘stan::math::var’ to ‘stan::math::vari*’ for argument ‘1’ to ‘void stan::math::grad(stan::math::vari*)’
         stan::math::grad(adLogProb, ad_params_r, gradient);
```

**Comment by syclik** [comment] 2016-11-16 20:21
What do you mean "this is another error"? I've seen a lot of our compiler errors, so if you can paste the whole error message, I might be able to guess at what's going on. Once something fails, the subsequent error messages don't usually help.

**Comment by ariddell** [comment] 2016-11-16 20:25
Attached!
[cov_quad_exp_error.txt](https://github.com/stan-dev/pystan/files/595820/cov_quad_exp_error.txt)

**Comment by syclik** [comment] 2016-11-16 20:59
Hmm. gcc 6? I haven't tried with that compiler. Do you have access to another compiler? I don't see anything wrong and you're right: the later error you posted is the relevant one. Not sure why it would try to convert automatically.

**Comment by nesanders** [comment] 2016-11-16 21:25
Hi Dan and Allen,

Thanks so much for taking a look at this.  Allen asked me to post the output of `python gp_cov_minimaltestcase.py &> error.txt`, which is attached

[error.txt](https://github.com/stan-dev/pystan/files/595957/error.txt)

**Comment by syclik** [comment] 2016-11-16 22:07
Thanks, both.

I was able to replicate it locally with CmdStan. I don't know what's
causing the issue yet, but I'm opening up an issue there. I'll link it back
to this issue.

Sorry about the wild goose-chase. I thought we had test coverage for the
different cases, but clearly not.

**Comment by syclik** [comment] 2016-11-17 14:37
@nesanders, here's what I do to build a custom version of pystan. @ariddell helped me get this set up -- is this anywhere in the doc?

First, I clone pystan and all its submodules (stan and math). Then from within the pystan folder, I type this:
```
python3 setup.py build_ext --inplace
```

And that does it. If I open python3 and start running pystan, it'll use whatever local version I have.

**Comment by syclik** [comment] 2016-11-17 14:38
I'm also closing this since it's this is fixed for the next version.

**Closed by syclik** 2016-11-17 14:38 UTC

**Comment by nesanders** [comment] 2016-11-18 14:30
Thank you, Daniel!  I'm afraid I haven't quite gotten it to work, though.  

Below I've written up the steps I took to install the devel version and the error I receive when compiling the MWE.  It returns the error right away with what looks like a numpy version issue, so I'm assuming it's just a problem with how I compiled the devel version.

Thanks in advance for any further guidance!

### Install approach

Clone the devel branch of pystan to a new directory:

`git clone -b develop https://github.com/stan-dev/pystan.git`

Clone the devel branch of stan to the subdirectory pystan/stan/

```
cd pystan/pystan
git clone -b develop https://github.com/stan-dev/stan.git
```

Clone the devel branch of stan-math to pystan/stan/lib/stan_math

```
cd stan/lib/
git clone -b develop https://github.com/stan-dev/math.git
rmdir stan_math
mv math/ stan_math
cd ../../..
```

Before running setup.py, I found I needed to adjust some of the includes in that script to match the directory structure created by those checkouts:

```
stan_include_dirs = ['pystan/stan/src',
		     'pystan/stan/lib/stan_math/',
                     'pystan/stan/lib/stan_math/lib/eigen_3.2.9',
                     'pystan/stan/lib/stan_math/lib/boost_1.60.0',
                     'pystan/stan/lib/stan_math/lib/cvodes_2.9.0/include'
                     ]
```

Then run `python setup.py build_ext --inplace` (or python3 if you're using version 3)

Then add this directory to the system path in python before importing:
```

import sys
sys.path.insert(0, **path**+'/pystan/')
import pystan
```

### Error
```

In [5]: stan_model_compiled = pystan.StanModel(file = 'gp_cov_minimaltestcase.stan', verbose=True)
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_a542b55e3040237e5430914c0437c8b4 NOW.
INFO:pystan:OS: linux2, Python: 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2], Cython 0.24.1
Compiling /tmp/tmpGxdV04/stanfit4anon_model_a542b55e3040237e5430914c0437c8b4_2019843158317082512.pyx because it changed.
[1/1] Cythonizing /tmp/tmpGxdV04/stanfit4anon_model_a542b55e3040237e5430914c0437c8b4_2019843158317082512.pyx
building 'stanfit4anon_model_a542b55e3040237e5430914c0437c8b4_2019843158317082512' extension
creating /tmp/tmpGxdV04/tmp
creating /tmp/tmpGxdV04/tmp/tmpGxdV04
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I/tmp/tmpGxdV04 -I/home/nes/Stan/pystan/pystan -I/home/nes/Stan/pystan/pystan/stan/src -I/home/nes/Stan/pystan/pystan/stan/lib/stan_math_2.12.0 -I/home/nes/Stan/pystan/pystan/stan/lib/stan_math_2.12.0/lib/eigen_3.2.9 -I/home/nes/Stan/pystan/pystan/stan/lib/stan_math_2.12.0/lib/boost_1.60.0 -I/home/nes/Stan/pystan/pystan/stan/lib/stan_math_2.12.0/lib/cvodes_2.8.2/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/tmpGxdV04/stanfit4anon_model_a542b55e3040237e5430914c0437c8b4_2019843158317082512.cpp -o /tmp/tmpGxdV04/tmp/tmpGxdV04/stanfit4anon_model_a542b55e3040237e5430914c0437c8b4_2019843158317082512.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/tmpGxdV04/stanfit4anon_model_a542b55e3040237e5430914c0437c8b4_2019843158317082512.cpp:338:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /tmp/tmpGxdV04/stanfit4anon_model_a542b55e3040237e5430914c0437c8b4_2019843158317082512.cpp:342:0:
/home/nes/Stan/pystan/pystan/stan_fit.hpp:13:59: fatal error: boost/date_time/posix_time/posix_time_types.hpp: No such file or directory
 #include <boost/date_time/posix_time/posix_time_types.hpp>
                                                           ^
compilation terminated.

```

**Comment by nesanders** [comment] 2016-11-20 20:48
Hi @ariddell and @syclik,

I've spent a few hours messing with this custom build process today and not gotten it to work...  I was wondering if you can help me find where my process described below goes wrong.

I won't waste your time with a summary of the N different things I've tried today, but here's a few things I've learned - 

* I think the numpy warning I referred to earlier was clearly incidental and not really a problem, as far as I can tell.  At root, I think the issue is a path problem for the stan includes.  

* In my previous comment I described some modifications I had to make to the paths in setup.py.  I think it's necessary to make analagous edits to the model.py file, as below, which seems to resolve some errors.  (Note also that the devel branch is now using boost 1.62.0)

```
sed -i 's/stan_math_2.12.0/stan_math/' pystan/model.py
sed -i 's/boost_1.60.0/boost_1.62.0/' pystan/model.py
sed -i 's/cvodes_2.8.2/cvodes_2.9.0/' pystan/model.py
```

* Now I get an error about util.hpp being missing.  Is this related to https://github.com/stan-dev/stan/issues/2049 ?

```
In file included from /tmp/tmpFTi1H7/stanfit4anon_model_a542b55e3040237e5430914c0437c8b4_2019704726419787337.cpp:343:0:
/home/nes/Stan/pystan_retry2/pystan/pystan/stan_fit.hpp:18:31: fatal error: stan/model/util.hpp: No such file or directory
 #include <stan/model/util.hpp>
                               ^
compilation terminated.
```

Thanks again for your help!

**Comment by ariddell** [comment] 2016-11-22 12:08
2.13 should be out very soon. Nathan, any interest in contributing your
test as a PR so we can make absolutely sure that we don't release PyStan
without support for cov_exp_quad?

**Comment by nesanders** [comment] 2016-11-22 12:52
Hi Allen,

I would be glad to.  Would that mean simply adding a scipt to pystan/tests?  What kind of assertion would you make to test compilation?

**Comment by ariddell** [comment] 2016-11-28 02:33
You can just do a self.assertIsNotNone(model) after compiling, there are a few examples of this kind of thing in pystan/tests, I think. Thanks!
