### ISSUE TITLE
_chains.effective_sample_size silently fails with Cython >= 0.23.3

### ISSUE THREAD

**Issue by stephen-hoover** [stan-dev/pystan#186] opened 2015-10-29 23:50 UTC
I noticed that something was strange with the determination of the effective number of samples -- when I printed the fit object every parameter always reported n_eff was equal to the total number of post-warmup draws. I traced this to the `effective_sample_size` function in "_chains.pyx". The calculation of the chain variance at https://github.com/stan-dev/pystan/blob/develop/pystan/_chains.pyx#L129 results in "inf", so `rho_hat >= 0` in https://github.com/stan-dev/pystan/blob/develop/pystan/_chains.pyx#L146 always evaluates to False.

I find the following strange things when I put in print statements:
```
acov[chain][0]: 2.336260998872636; Kept samples: 500

n_kept_samples / (n_kept_samples-1) = 1.002004008016032
acov[chain][0] * n_kept_samples = 1168.130499436318
acov[chain][0] * n_kept_samples / (n_kept_samples-1) = inf
```
This is with both Cython 0.23.3 and 0.23.4. When I downgrade to Cython 0.19, the infinity disappears, so Cython is doing something strange here. I haven't bothered to dive into the generated C code.

The solution looks simple: in the line https://github.com/stan-dev/pystan/blob/develop/pystan/_chains.pyx#L125, change `cdef int n_kept_samples` to `cdef double n_kept_samples`. Then the calculation of effective sample size works in both Cython 0.19 and the newest Cython version. Perhaps it would be worth adding a check that this value isn't infinity.

**Comment by stephen-hoover** [comment] 2015-10-30 13:41
This appears to be the same issue as #184 . I'm running this under Python 3.5, in case that's also related.

**Comment by ariddell** [comment] 2015-10-30 14:19
Thanks! I'm working on this right now.

This one is particularly vexing because I can't reproduce it on my system (Linux, Python 3.4). I'll try out Python 3.5.

I'll get to the bottom of this soon. Thanks very much for the reports.

**Comment by stephen-hoover** [comment] 2015-10-30 15:02
I see this problem on both Ubuntu 14.04 and OS X 10.10.4, with Cython 0.23.3 or newer (I didn't try older versions of Cython aside from 0.19). I also see it with both Python 3.4.3 and 3.5.

**Comment by ariddell** [comment] 2015-10-30 19:27
Should be fixed by 2b126b5

**Closed by ariddell** 2015-10-30 19:27 UTC

**Comment by stephen-hoover** [comment] 2015-10-30 19:43
Thanks! Looks like it's working to me.

**Comment by ariddell** [comment] 2015-10-31 07:39
Reported to cython-users. Thanks again Stephen.
