### ISSUE TITLE
distutils.errors.CompileError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by aeleuterio** [stan-dev/pystan#219] opened 2016-03-22 20:50 UTC
#### Summary:
Compilation error on Pystan 2.9.0.0 with Stan 2.9.0.

#### Description:
I am running Pystan on a Linux environment with no internet connection, so I installed everything from source. I am running Python 2.7.7 and gcc 4.8.3. When trying to run the Eight Schools example, I get the output below.
Notes: The same example runs on my RStan installation and on the previous Pystan installation (2.2.0.0). I have tried building Pystan and running the example with several different compilers. Also, another example (Neal Funnel) gives the same output.
I have debugged the compilation down to the gcc call for the model but it was way over my head. My next steps were to install pieces separately (stan and stan_math) and no combination worked.

#### Current Output:
`
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_95013624776d537c3cd7cd4d641c30e0 NOW.
Traceback (most recent call last):
  File "eightschools.py", line 33, in <module>
    iter=1000, chains=4)
  File "/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packages/pystan/api.py", line 368, in stan
    verbose=verbose)
  File "/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packages/pystan/model.py", line 312, in __init__
    build_extension.run()
  File "/apps/python/2.7.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/apps/python/2.7.7/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
    self.build_extension(ext)
  File "/apps/python/2.7.7/lib/python2.7/distutils/command/build_ext.py", line 496, in build_extension
    depends=ext.depends)
  File "/apps/python/2.7.7/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/apps/python/2.7.7/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
    raise CompileError, msg
distutils.errors.CompileError: command 'gcc' failed with exit status 1`

#### Expected Output:
`INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_95013624776d537c3cd7cd4d641c30e0 NOW.
INFO:pystan:NOW ON CHAIN 0
INFO:pystan:NOW ON CHAIN 1
INFO:pystan:NOW ON CHAIN 2
INFO:pystan:NOW ON CHAIN 3
Iteration: 1000 / 1000 [100%]  (Sampling)
Elapsed Time: 0.01 seconds (Warm-up)
              0.01 seconds (Sampling)
              0.02 seconds (Total)

Iteration: 1000 / 1000 [100%]  (Sampling)
Elapsed Time: 0.01 seconds (Warm-up)
              0.01 seconds (Sampling)
              0.02 seconds (Total)

Iteration: 1000 / 1000 [100%]  (Sampling)
Elapsed Time: 0.01 seconds (Warm-up)
              0.01 seconds (Sampling)
              0.02 seconds (Total)

Iteration: 1000 / 1000 [100%]  (Sampling)
Elapsed Time: 0.01 seconds (Warm-up)
              0.02 seconds (Sampling)
              0.03 seconds (Total)`

#### PyStan Version:
2.9.0.0
#### Python Version:
2.7.7
#### Operating System:
CentOS

Thank you in advance

**Comment by ariddell** [comment] 2016-03-22 22:41
My initial guess is that there's a conflict with the old version of PyStan. Clearly you have a new version of gcc, so that's not the problem.

The next step is to compile the model with ``verbose=True`` and get the full error output. Would you mind doing that? If you're doing the 8 schools example just add ``verbose=True`` to the parameters:

```
pystan.stan(model_code=schools_code, data=schools_dat, iter=1000, chains=4, verbose=True)
```

**Comment by aeleuterio** [comment] 2016-03-23 17:09
Here's the output with `verbose=True`:
`INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_95013624776d537c3cd7cd40e0 NOW.
INFO:pystan:OS: linux2, Python: 2.7.7 (default, Jan  9 2015, 00:11:44)
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)], Cython 0.21.2
missing cimport in module '.utility': /apps/python/2.7.7/lib/python2.7/site-pacCython/Includes/libcpp/pair.pxd
missing cimport in module '.utility': /apps/python/2.7.7/lib/python2.7/site-pacCython/Includes/libcpp/map.pxd
Compiling /tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5076256523903.pyx because it changed.
Cythonizing /tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_6376256523903.pyx
building 'stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_50981863762565239tension
creating /tmp/tmpQUqQlw/tmp
creating /tmp/tmpQUqQlw/tmp/tmpQUqQlw
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstricttypes -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERIGEN_NO_DEBUG -I/tmp/tmpQUqQlw -I/home/workgroups/reit/apps/python/2.7.7/pystan.0/lib/python2.7/site-packages/pystan -I/home/workgroups/reit/apps/python/2.7.7n/2.9.0.0/lib/python2.7/site-packages/pystan/stan/src -I/home/workgroups/reit/athon/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packages/pystan/stan/lib/stan_mathme/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packagesn/stan/lib/stan_math/lib/eigen_3.2.4 -I/home/workgroups/reit/apps/python/2.7.7//2.9.0.0/lib/python2.7/site-packages/pystan/stan/lib/stan_math/lib/boost_1.58.0ps/python/2.7.7/lib/python2.7/site-packages/numpy/core/include -I/apps/python/2nclude/python2.7 -c /tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d60_5098186376256523903.cpp -o /tmp/tmpQUqQlw/tmp/tmpQUqQlw/stanfit4anon_model_95776d537c3cd7cd4d641c30e0_5098186376256523903.o -O2 -ftemplate-depth-256 -Wno-ununction -Wno-uninitialized
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjCot for C++ [enabled by default]
In file included from /apps/python/2.7.7/lib/python2.7/site-packages/numpy/corede/numpy/ndarraytypes.h:1781:0,
                 from /apps/python/2.7.7/lib/python2.7/site-packages/numpy/corede/numpy/ndarrayobject.h:18,
                 from /apps/python/2.7.7/lib/python2.7/site-packages/numpy/corede/numpy/arrayobject.h:4,
                 from /tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd40e0_5098186376256523903.cpp:247:
/apps/python/2.7.7/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7cated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by fining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/lib/boost_1.58.0/boost/multi_arra.hpp:28:0,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/lib/boost_1.58.0/boost/multi_arra21,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/lib/boost_1.58.0/boost/numeric/odtil/multi_array_adaption.hpp:29,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/lib/boost_1.58.0/boost/numeric/odpp:61,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/stan/math/prim/arr/functor/integre.hpp:12,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/stan/math.hpp:65,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/src/stan/variational/advi.hpp:4,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan_fit.hpp:83,
                 from /tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd40e0_5098186376256523903.cpp:251:
/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packastan/stan/lib/stan_math/lib/boost_1.58.0/boost/multi_array/concept_checks.hpp: tic member function 'static void boost::multi_array_concepts::detail::idgen_hel::call(Array&, const IdxGen&, Call_Type)':
/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packastan/stan/lib/stan_math/lib/boost_1.58.0/boost/multi_array/concept_checks.hpp:4warning: typedef 'index_range' locally defined but not used [-Wunused-local-typ
       typedef typename Array::index_range index_range;
                                           ^
/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packastan/stan/lib/stan_math/lib/boost_1.58.0/boost/multi_array/concept_checks.hpp:4warning: typedef 'index' locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^
/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packastan/stan/lib/stan_math/lib/boost_1.58.0/boost/multi_array/concept_checks.hpp: tic member function 'static void boost::multi_array_concepts::detail::idgen_hell>::call(Array&, const IdxGen&, Call_Type)':
/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packastan/stan/lib/stan_math/lib/boost_1.58.0/boost/multi_array/concept_checks.hpp:5warning: typedef 'index_range' locally defined but not used [-Wunused-local-typ
       typedef typename Array::index_range index_range;
                                           ^
/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packastan/stan/lib/stan_math/lib/boost_1.58.0/boost/multi_array/concept_checks.hpp:5warning: typedef 'index' locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^
In file included from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/stan/math.hpp:80:0,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/src/stan/variational/advi.hpp:4,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan_fit.hpp:83,
                 from /tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd40e0_5098186376256523903.cpp:251:
/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packastan/stan/lib/stan_math/stan/math/prim/mat/err/check_positive_ordered.hpp: In fn 'bool stan::math::check_positive_ordered(const char*, const char*, const Eigerix<Scalar, -1, 1>&)':
/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packastan/stan/lib/stan_math/stan/math/prim/mat/err/check_positive_ordered.hpp:39:67ing: typedef 'size_type' locally defined but not used [-Wunused-local-typedefs]
       typedef typename index_type<Matrix<T_y, Dynamic, 1> >::type size_type;
                                                                   ^
/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp: In function 'PyObject* __pyx_pf_71stanfit4anon_model_95013624776d537c3cd41c30e0_5098186376256523903_2_call_sampler(PyObject*, PyObject*, PyObject*, PyO)':
/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp:7812:71: warning: comparison between signed and unsigned integer expressiWsign-compare]
     __pyx_t_12 = ((__pyx_t_9 != __pyx_v_fitptr->param_names_oi().size()) != 0)
                                                                       ^
/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp: In function 'std::vector<long unsigned int> __pyx_convert_vector_from_pyt(PyObject*)':
/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp:18619:81: warning: comparison between signed and unsigned integer express-Wsign-compare]
     __pyx_t_5 = __Pyx_PyInt_As_size_t(__pyx_v_item); if (unlikely(__pyx_t_5 == PyErr_Occurred())) {__pyx_filename = __pyx_f[7]; __pyx_lineno = 52; __pyx_clin__LINE__; goto __pyx_L1_error;}

/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp:418:43: note: in definition of macro 'unlikely'
   #define unlikely(x) __builtin_expect(!!(x), 0)
                                           ^
/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp: In function 'std::vector<std::basic_string<char> > __pyx_convert_vector_y_std_3a__3a_string(PyObject*)':
/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp:19133:34: **error: redefinition of 'std::vector<std::basic_string<char> > _onvert_vector_from_py_std_3a__3a_string(PyObject*)'
 static std::vector<std::string>  __pyx_convert_vector_from_py_std_3a__3a_strinject *__pyx_v_o)** {
                                  ^
/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp:19022:34: **error: 'std::vector<std::basic_string<char> > __pyx_convert_vecom_py_std_3a__3a_string(PyObject*)' previously defined here
 static std::vector<std::string>  __pyx_convert_vector_from_py_std_3a__3a_strinject *__pyx_v_o)** {
                                  ^
/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp: In function 'std::vector<unsigned int> __pyx_convert_vector_from_py_unsint(PyObject*)':
/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp:19321:87: warning: comparison between signed and unsigned integer express-Wsign-compare]
     __pyx_t_5 = __Pyx_PyInt_As_unsigned_int(__pyx_v_item); if (unlikely(__pyx_ -1 && PyErr_Occurred())) {__pyx_filename = __pyx_f[13]; __pyx_lineno = 52; __pneno = __LINE__; goto __pyx_L1_error;}
                                                                                 ^
/tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5098186376253.cpp:418:43: note: in definition of macro 'unlikely'
   #define unlikely(x) __builtin_expect(!!(x), 0)
                                           ^
In file included from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/stan/math/rev/core/operator_unaryhpp:7:0,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/stan/math/rev/core.hpp:34,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/stan/math/rev/mat/fun/Eigen_NumTrpp:4,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/lib/stan_math/stan/math/rev/mat/fun/grad.hpp:6,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan/src/stan/model/util.hpp:7,
                 from /home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lion2.7/site-packages/pystan/stan_fit.hpp:18,
                 from /tmp/tmpQUqQlw/stanfit4anon_model_95013624776d537c3cd7cd40e0_5098186376256523903.cpp:251:
/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packastan/stan/lib/stan_math/stan/math/prim/scal/fun/constants.hpp: At global scope:
/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/site-packastan/stan/lib/stan_math/stan/math/prim/scal/fun/constants.hpp:66:18: warning: 'math::NEGATIVE_EPSILON' defined but not used [-Wunused-variable]
     const double NEGATIVE_EPSILON
                  ^
Traceback (most recent call last):
  File "eightschools.py", line 33, in <module>
    iter=1000, chains=4, verbose=True)
  File "/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/sikages/pystan/api.py", line 368, in stan
    verbose=verbose)
  File "/home/workgroups/reit/apps/python/2.7.7/pystan/2.9.0.0/lib/python2.7/sikages/pystan/model.py", line 312, in __init__
    build_extension.run()
  File "/apps/python/2.7.7/lib/python2.7/distutils/command/build_ext.py", line n run
    self.build_extensions()
  File "/apps/python/2.7.7/lib/python2.7/distutils/command/build_ext.py", line n build_extensions
    self.build_extension(ext)
  File "/apps/python/2.7.7/lib/python2.7/distutils/command/build_ext.py", line n build_extension
    depends=ext.depends)
  File "/apps/python/2.7.7/lib/python2.7/distutils/ccompiler.py", line 574, in e
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/apps/python/2.7.7/lib/python2.7/distutils/unixccompiler.py", line 122,ompile
    raise CompileError, msg
distutils.errors.CompileError: command 'gcc' failed with exit status 1`

I noticed how it says I'm running gcc 4.8.3. But look:
`$ which gcc
/apps/gnu/gcc/4.8.3/bin/gcc`

**Comment by ariddell** [comment] 2016-03-23 17:55
It looks like Python is using a different gcc which might be the source
of the problem. You can see on the third line that Python is
using the (default?) gcc compiler for your version of CentOS:

> [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)], Cython 0.21.2

But gcc might not be the problem. It could be Cython. Would you mind
installing a newer version of Cython (current version is 0.23.x) and see
if that fixes the problem?

If it fixes the problem we can blacklist Cython 0.21.2 so others do not
encounter this problem in the future.

**Comment by aeleuterio** [comment] 2016-03-23 18:43
@ariddell You are correct, it was Cython. As soon as I loaded Cython 0.23.x it worked.
I would also suggest to revise the documentation page; it says Cython >=0.19.
Thank you very much for you help

**Comment by ariddell** [comment] 2016-03-23 19:13
Thanks again for reporting this. I'm glad we solved the problem.

Where do you see Cython>=0.19?

**Comment by aeleuterio** [comment] 2016-03-23 19:28
https://pystan.readthedocs.org/en/latest/getting_started.html

**Comment by ariddell** [comment] 2016-03-23 21:40
Thanks. The documentation is fixed now.

I'm still surprised you were able to install from source with the old
Cython. If you look at setup.py in the 2.9.0 source you can see the
Cython requirement of '>= 0.22'. Can you tell me how you
upgraded/installed from source? Did you run 'python setup.py install'?
It would be helpful to reproduce this bug and understand why setup.py
didn't prompt you to upgrade Cython.

**Comment by aeleuterio** [comment] 2016-03-24 13:12
@ariddell I installed it several times, in different ways. With python setup.py install, setup.py build and then install, etc. I was never prompted to upgrade Cython

**Comment by ariddell** [comment] 2016-03-24 15:48
OK. I'll look into this. Thanks.

**Closed by ariddell** 2016-03-24 15:48 UTC

**Comment by xiachongkun** [comment] 2017-08-08 13:30
I also have this mistake. My Cython version is 0.26.But it didn't work !! Do you have solved it ?How do you solve it ? I feel I will die~~~Can you help me ? This is my issue: https://github.com/openai/mujoco-py/issues/88

**Comment by jackSDU** [comment] 2017-11-04 05:59
Same mistake with Cython '0.27' :(

**Comment by ahartikainen** [comment] 2017-11-04 08:06
Are these error PyStan related?

If they are,
what was the error message?

**Comment by jackSDU** [comment] 2017-11-07 07:47
Probably not, i've just found that it has no problem with raw ipython, but got some problem in Spyder.

**Comment by ahartikainen** [comment] 2017-11-07 09:34
They are probably in different environments?

**Comment by jackSDU** [comment] 2017-11-08 04:58
I think they are the same,both are installed under anaconda.I'll check it in more detail though.
Now i'm pretty sure the error is not related to pystan,thanks a lot :)
