### ISSUE TITLE
Ability to build without data

### ISSUE THREAD

**Issue by smoh** [stan-dev/pystan#251] opened 2021-03-27 19:44 UTC
I would like to compile the model without providing the data. Although the [documentation for build function](https://pystan.readthedocs.io/en/latest/reference.html#stan.build) says `data` is optional, it seems to be required otherwise, I get the following kind of runtime error:

```python
RuntimeError: Error calling get_param_names: `Exception: variable does not exist; processing stage=data initialization; variable name=J; base type=int (in '/tmp/httpstan_5zon5nsd/model_o6xtocu7.stan', line 3, column 2 to column 17)`
```
and in fact, data keyword is not permitted at `posterior.sample` stage (https://github.com/stan-dev/pystan/blob/main/stan/model.py#L123).

As I understand, the reason why this is so is that the `Model` class is to be treated as "frozen" posterior (specified by a combination of stan model and data) with information about the shape of the constrained parameters which can often depend on the shape of the data. (https://github.com/stan-dev/httpstan/blob/main/httpstan/views.py#L226)

However, I think it is still useful to be able to compile the model without the data. Would this be something maintainers consider implementing?

This seems possible as httpstan which is used under the hood has that ability (https://httpstan.readthedocs.io/en/latest/rest_api.html#post--v1-models) but right now, `build` uses `/models/<model_id>/params` (https://httpstan.readthedocs.io/en/latest/rest_api.html#post--v1-models-model_id-params) which requires data payload (the documentation is missing this fact https://httpstan.readthedocs.io/en/latest/rest_api.html#post--v1-models-model_id-params)

I'll just quickly recap the inconsistencies I've found:
- Unlike what the function signature says, `data` is not optional but required in stan.build.
- REST API documentation of httpstan for `/models/<model_id>/params` is missing Request Json Object "data".

**Comment by riddell-stan** [comment] 2021-03-27 22:27
Thanks for the report. It's great to have help identifying some of the loose ends. The documentation definitely needs to be fixed.

IIRC, pystan/httpstan requires the data when the model is instantiated because that's what Stan C++ requires (when the ``stan::model::model_base`` instance is created). You can see what is happening if you look at the C++ code generated by stanc.

There's more than one reason that the Stan C++ library does this. If you're curious, you might consider asking on the Stan forum.

For the compilation-without-model-initialization task, do you have a specific use case in mind?

**Comment by smoh** [comment] 2021-03-27 22:46
> IIRC, pystan/httpstan requires the data when the model is instantiated because that's what Stan C++ requires (when the `stan::model::model_base` instance is created). You can see what is happening if you look at the C++ code generated by stanc.
> 
> There's more than one reason that the Stan C++ library does this. If you're curious, you might consider asking on the Stan forum.

I'm a little confused because [`POST /models`](https://httpstan.readthedocs.io/en/latest/rest_api.html#post--v1-models) does say "Compie a stan model" with only model code as input. Isn't this compiling without data? Also, from just fiddling with the eight schools, it seemed that changing data by e.g., putting one more entry seemed to load the cached model compiled with the previous different data, i.e., changing `data` to`stan.build` without changing the stan code does not recompile.

> 
> For the compilation-without-model-initialization task, do you have a specific use case in mind?

For example, previously with pystan2, I was able to pre-compile and cache all models in advance without needing to specify the data (although that functionality wasn't officially in the pystan2). https://pystan2.readthedocs.io/en/latest/avoiding_recompilation.html

I also personally thought it conceptually makes more sense to separate out model building from actually sampling that model with a specific set of data. (Although technically, if you have, for example, a parameter with variable length that equals the size of the data like in eight schools, you may say that the models with different `J`  are different models).

**Comment by smoh** [comment] 2021-03-27 23:31
I guess a hacky way to do what I wanted to do is to provide empty data once initially

```sh
❯ cat pystan3-test.py
if __name__ == "__main__":
    import stan

    schools_code = """
    data {
      int<lower=0> J;         // number of schools
      real y[J];              // estimated treatment effects
      real<lower=0> sigma[J]; // standard error of effect estimates
    }
    parameters {
      real mu;                // population treatment effect
      real<lower=0> tau;      // standard deviation in treatment effects
      vector[J] eta;          // unscaled deviation from mu by school
    }
    transformed parameters {
      vector[J] theta = mu + tau * eta;        // school treatment effects
    }
    model {
      target += normal_lpdf(eta | 0, 1);       // prior log-density
      target += normal_lpdf(y | theta, sigma); // log-likelihood
    }
    """

    schools_data = {"J": 8,
                    "y": [28,  8, -3,  7, -1,  1, 18, 12],
                    "sigma": [15, 10, 16, 11,  9, 11, 10, 18]}
    empty_data = dict(J=0, y=[], sigma=[])

    print("with empty data")
    posterior0 = stan.build(schools_code, data=empty_data)
    print("with actual data")
    posterior1 = stan.build(schools_code, data=schools_data)
    # fit = posterior.sample(num_chains=2, num_samples=1000)

❯ python pystan3-test.py
with empty data
Building... This may take some time.
Messages from stanc:
Warning:
  The parameter mu has no priors.
Warning:
  The parameter tau has no priors.
Done.
with actual data
Building...
Messages from stanc:
Warning:
  The parameter mu has no priors.
Warning:
  The parameter tau has no priors.
Found model in cache. Done.
```

**Comment by riddell-stan** [comment] 2021-03-28 12:51
There are a couple of different issues here. Glad you found something that works.

PyStan 3, by design, doesn't separate out the compilation step.

I'm going to close this for now. I'll create a new issue for the documentation problem. If you want, feel free to create a new issue about the ability to build without data. Please provide a use case and indicate that you're proposing a change to the *design* of PyStan 3. There's no technical barrier to adding a separate compilation step, so there's no need to mention that.

**Closed by riddell-stan** 2021-03-28 12:51 UTC

**Comment by ahartikainen** [comment] 2021-03-28 16:55
I can add couple of comments to the discussion.


First, I understand this workflow might feel a bit weird, but let's think about it

1. pystan is a shim -> creating same model should not be an issue, httpstan handles caching, so user should not worry about it.
2. I think model = stan model + data is needed for prng -> reproducible workflow

After initial friction we probably can come back to this issue. 

e.g. it took me some time before this  workflow felt natural.

ps. We should also comsider what is the correct workflow to debug Stan files (.stan). I many times don't have data at hand, but still I want to see that model can be compiled. (stanc call helps here).

**Comment by smoh** [comment] 2021-03-29 12:59
Thanks for your responses and clearing up the documentation with #252 ! I can understand that enforcing input data at the model building stage certainly promotes a more reproducible workflow.

For now, I have found a workaround to do what I wanted to do, and I guess I don't have an opinion strong enough to suggest any more changes.
