### ISSUE TITLE
error installing pystan into anaconda 3.6 on windows 8.1,

### ISSUE THREAD

**Issue by stefangeorge** [stan-dev/pystan#306] opened 2017-03-01 02:33 UTC
'pip install pystan' fails

I followed the instructions [here](http://pystan.readthedocs.io/en/latest/windows.html):

1) installed anaconda 3.6
2) ran `pip install setuptools`
3) downloaded Visual C++ 2015 Build Tools from [here](http://landinghub.visualstudio.com/visual-cpp-build-tools)
4) ran `pip install pystan`
5) got:
```
Collecting pystan                                                                                                                                             
  Using cached pystan-2.14.0.0.tar.gz                                                                                                                         
Requirement already satisfied: Cython!=0.25.1,>=0.22 in c:\users\stefan\anaconda3\lib\site-packages (from pystan)                                             
Requirement already satisfied: numpy>=1.7 in c:\users\stefan\anaconda3\lib\site-packages (from pystan)                                                        
Building wheels for collected packages: pystan                                                                                                                
  Running setup.py bdist_wheel for pystan ... error                                                                                                           
  Complete output from command C:\Users\Stefan\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-
build-sg3jgjud\\pystan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec
'))" bdist_wheel -d C:\Users\Stefan\AppData\Local\Temp\tmpt9gbmbwspip-wheel- --python-tag cp36:                                                               
  running bdist_wheel                                                                                                                                         
  running build                                                                                                                                               
  running build_py                                                                                                                                            
  creating build                                                                                                                                              
  creating build\lib.win-amd64-3.6                                                                                                                            
  creating build\lib.win-amd64-3.6\pystan                                                                                                                     
  copying pystan\api.py -> build\lib.win-amd64-3.6\pystan
```                                                                                                     
~lots of lines copying pystan code to `build\lib.win-amd64-3.6\pystan\stan\`directories
then
 ```
error: could not create 'build\lib.win-amd64-3.6\pystan\stan\lib\stan_math_2.14.0\doc\api\html\d0\d0f\structstan_1_1is__vector__like_3_01_eigen_1_1_matrix_3_01_t_00_01_eigen_1_1_dynamic_00_01_eigen_1_1_dynamic_01_4_01_4-members.html': No such file or directory

  ----------------------------------------
Failed building wheel for pystan
Running setup.py clean for pystan
Failed to build pystan
Installing collected packages: pystan
Running setup.py install for pystan ... error
Complete output from command C:\Users\Stefan\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-build-kwo3kxn5\\pystan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Stefan\AppData\Local\Temp\pip-u49wmsu9-record\install-record.txt --single-version-externally-managed --compile:
running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pystan
    copying pystan\api.py -> build\lib.win-amd64-3.6\pystan
```
then lots more lines copying pystan code to `build\lib.win-amd64-3.6\pystan\stan\`directories
and ending with
```
    error: could not create 'build\lib.win-amd64-3.6\pystan\stan\lib\stan_math_2.14.0\doc\api\html\d0\d0f\structstan_1_1is__vector__like_3_01_eigen_1_1_matrix_3_01_t_00_01_eigen_1_1_dynamic_00_01_eigen_1_1_dynamic_01_4_01_4-members.html': No such file or directory

    ----------------------------------------
Command "C:\Users\Stefan\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Stefan\\AppData\\Local\\Temp\\pip-build-sg3jgjud\\pystan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Stefan\AppData\Local\Temp\pip-pi4y6r4_-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Stefan\AppData\Local\Temp\pip-build-sg3jgjud\pystan\
```

I should note this machine had Visual Studio 2013 and 2015 installed as it was used for dev work. The Visual C++ 2015 Build Tools were added on top as a recent compiler is required by anaconda 3.6 and pystan.

**Comment by stefangeorge** [comment] 2017-03-01 03:03
just tried the same procedure on a virgin windows 10 box. same error.
bottom line:

`Command "C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\George\\AppData\\Local\\Temp\\pip-build-fl5amolq\\pystan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\George\AppData\Local\Temp\pip-lu6hy0vv-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\George\AppData\Local\Temp\pip-build-fl5amolq\pystan\`

**Comment by stefangeorge** [comment] 2017-03-01 03:10
I did find a pystan package here:
```
$ anaconda show patricksnape/pystan
Using Anaconda API: https://api.anaconda.org
Name:    pystan
Summary:
Access:  public
Package Types:  conda
Versions:
   + 2.2.0.0
   + 2.3.0.0
   + 2.4.0.3
   + 2.5.0.1
   + 2.7.0.0
```
tried to install it but it seems not to like anaconda 3.6

```
conda install --channel https://conda.anaconda.org/patricksnape pystan
Fetching package metadata .............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - pystan -> numpy 1.9* -> python 2.6*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by ariddell** [comment] 2017-03-01 14:47
There are no pre-compiled Python 3.6 wheels on Windows. I'll look into fixing this. Might not fix your specific problem but it probably wouldn't hurt.

**Comment by ariddell** [comment] 2017-03-01 15:06
I'm going to create an issue to make sure that Python 3.6 wheels for Windows are part of the next release. #307

**Comment by bob-carpenter** [comment] 2017-03-01 17:51
You really want Stan 2.14 and really don't want Stan 2.10--2.13.  

- Bob

**Comment by ahartikainen** [comment] 2017-03-03 06:23
Have you tried 

    pip install git+https://stan-dev/pystan

Are you using Anaconda/miniconda?

After you get install done please check all the test if they pass.

**Comment by sixteh** [comment] 2017-03-03 20:33
It looks like some of the documentation html files have such long filenames that, depending on where you have the files installed, exceeds the windows character limit for a file path.

Use something like:
`pip install pystan --t C:\ --no-dependencies`
Then copy the directory to \Lib\site-packages

**Comment by aamirc** [comment] 2017-03-07 01:30
@sixteh that pip command doesn't work in windows CMD

This works but throws out the same filepath error.

`pip install pystan --target C:\ --no-dependencies`

**Comment by WSC-SUJE** [comment] 2017-03-10 08:37
I'm having the same issue. 
Windows : 7-64bit
Python : 3.6

**Comment by ariddell** [comment] 2017-03-11 16:18
If you can install from source, just remove the entire directory ``pystan\stan\lib\stan_math_2.14.0\doc``. See if that does the trick. (The directory shouldn't be included anyway and will not be included in future releases).

I gather this is related to the 255 character limit for file paths on windows.

**Comment by fredericgirod** [comment] 2017-03-12 20:56
Any additional thoughts ?
It definitely doesn't work for me either...

**Comment by sixteh** [comment] 2017-03-12 22:32
Compile from source and delete or rename the file that threw the exception -- that's what worked for me.

**Comment by ariddell** [comment] 2017-03-13 13:07
@fredericgirod Try installing from source. ``build\lib.win-amd64-3.6\pystan\stan\lib\stan_math_2.14.0\doc\api\html\d0\d0f\structstan_1_1is__vector__like_3_01_eigen_1_1_matrix_3_01_t_00_01_eigen_1_1_dynamic_00_01_eigen_1_1_dynamic_01_4_01_4-members.html'`` is now (or should be) excluded from the build (#312 was just merged)

**Comment by fredericgirod** [comment] 2017-03-13 17:39
From source, is it the wheel file pystan-2.14.0.0-cp35-cp35m-win_amd64.whl, for windows ?

**Comment by ahartikainen** [comment] 2017-03-13 17:51
Clone from git (e.g. zip -> unzip >> cd to folder and do `python -v setup.py install`. `-v` for verbose.

There are still issues with windows compiler and stan (probably eigen library, due to bug in MSVC 14.0).

**Comment by fredericgirod** [comment] 2017-03-13 20:56
Thanks, but it is a failure for me:
----------------
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
building 'pystan._api' extension
error: Unable to find vcvarsall.bat

**Comment by WSC-SUJE** [comment] 2017-03-14 01:13
@ahartikainen, Thank you, but I failed to install. Error messages are as follows. Maybe I should give up the Windows environment..
=================================================
c:\Python36-32\pystan-develop>python setup.py install
Compiling pystan/_api.pyx because it changed.
Compiling pystan/_chains.pyx because it changed.
Compiling pystan/_misc.pyx because it changed.
[1/3] Cythonizing pystan/_api.pyx
[2/3] Cythonizing pystan/_chains.pyx
[3/3] Cythonizing pystan/_misc.pyx
running install
running build
running build_py
...............................
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
building 'pystan._api' extension
creating build\temp.win32-3.6
...............................
Found executable C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe
_api.cpp
c:\python36-32\pystan-develop\pystan\stanc.hpp(1): fatal error C1083: Cannot open include file: 'stan/version.hpp': No such file or directory
error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DBOOST_RESULT_OF_USE_TR1 -DBOOS
T_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen
_3.2.9 -Ipystan/stan/lib/stan_math/lib/boost_1.62.0 -Ipystan/stan/lib/stan_math/lib/cvodes_2.9.0/include -IC:\Python36-32\include -IC:\Python36-32\inc
lude -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Pro
gram Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\in
clude\winrt" /EHsc /Tppystan/_api.cpp /Fobuild\temp.win32-3.6\Release\pystan/_api.obj /EHsc -DBOOST_DATE_TIME_NO_LIB" failed with exit status 2

**Comment by ahartikainen** [comment] 2017-03-14 06:23
That is a problem with recursive clone failing. I don't know if that works with zipping.

Git command is

    git --recursive clone https://github.com/stan-dev/pystan.git

**Comment by fredericgirod** [comment] 2017-03-14 08:15
Definitely it doesn't work either way ...

Unknown option: --recursive

**Comment by ahartikainen** [comment] 2017-03-14 08:22
Oh, I put it before `clone`.

See official instructions here
https://github.com/stan-dev/pystan/blob/develop/README.rst

**Comment by fredericgirod** [comment] 2017-03-14 12:12
Many thanks.
It seems that I followed the instructions, but still got the same issues.

running install
running build
running build_py
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
building 'pystan._api' extension
error: Unable to find vcvarsall.bat

**Comment by ahartikainen** [comment] 2017-03-14 13:58
Please make sure you have the correct [compiler](https://wiki.python.org/moin/WindowsCompilers) installed and configured (see [here](https://msdn.microsoft.com/en-us/library/f2ccy3wt.aspx))

If you use Anaconda, please try to install in conda-env.

    conda create -n stan_env python=3.6 numpy cython matplotlib
    activate stan_env
    git clone --recursive https://github.com/stan-dev/pystan.git
    cd pystan
    python setup.py install

**Comment by lzucoffee** [comment] 2017-03-14 14:21
you can try python setup.py install.

**Comment by rolando** [comment] 2017-03-21 01:57
FYI, there are `pystan 2.14` packages in the `conda-forge` channel: `conda install -c conda-forge pystan`

**Comment by ariddell** [comment] 2017-03-21 12:33
Awesome. Thanks @rolando

**Comment by zhounanshu** [comment] 2017-04-17 01:19
Good Job, Thanks @rolando

**Comment by ariddell** [comment] 2017-04-18 17:04
Closing this for now. Open another issue of there's a problem with 2.15 (out soon).

**Closed by ariddell** 2017-04-18 17:04 UTC

**Comment by lizzyhuang** [comment] 2017-09-09 21:41
I have trouble compiling the example provided on the website. 

I am on Windows 10, 64bit, have Anaconda3, Python = 3.6

I first installed VS C++ build tools 2015, as the website suggests. Nothing wrong with the installation. 

Then I tried directly on the Windows command prompt 
```
pip install pystan
```
Everything seemed fine. So I tried to compile an example to make sure pystan works. I had no trouble importing pystan. I also have numpy and cyphon. But when I compiled the model, the error said:
```
CompileError: command 'cl.exe' failed: No such file or directory
```

I don't know what goes wrong. I searched through Google but this error only seems to happen when users are trying to install pystan, not when they're trying to use pystan. Anyone can help?

PS: I also tried to install pystan through the `conda-forge` channel, installed successfully but same compiling error.
I also tried to install directly through GitHub, say the one here
```
conda create -n stan_env python=3.6 numpy cython matplotlib
activate stan_env
git clone --recursive https://github.com/stan-dev/pystan.git
cd pystan
python setup.py install
```
I wasn't able to proceed. It said:
```
error: Command "cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -I.\pystan -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.3.3 -Ipystan/stan/lib/stan_math/lib/boost_1.62.0 -Ipystan/stan/lib/stan_math/lib/cvodes_2.9.0/include -IC:\Users\lizzy\Anaconda3\envs\stan_env\include -IC:\Users\lizzy\Anaconda3\envs\stan_env\include /EHsc /Tppystan/_api.cpp /Fobuild\temp.win-amd64-3.6\Release\pystan/_api.obj /EHsc -DBOOST_DATE_TIME_NO_LIB" failed with exit status 127
```
I also tried 
```
pip install git+https://stan-dev/pystan
```
failed directly.

**Comment by ahartikainen** [comment] 2017-09-09 22:53
It means that program can not find C++ msvc compiler (cl.exe). That is probably problem with your environmental variables. Have you runned the `vcvarsall.bat x64` command?

We have updated instructions for windows here using gcc https://github.com/stan-dev/pystan/issues/364

**Comment by lizzyhuang** [comment] 2017-09-09 23:42
I haven't run `vcvarsall.bat x64`. When should I run it?

So I followed the #364 but it still doesn't work. My computer has VS 2017 originally. According to the PyStan webpage, I also installed VS C++ build tools 2015 today. I don't know whether the two will conflict though. After receiving your reply, I did the following:
```
conda create -n stan_env python=3.6
activate stan_env
conda install numpy cython matplotlib scipy pandas
conda install libpython
conda install -c msys2 m2w64-toolchain=5.3.0
# I don't know what it means by "step with distutils.cfg" so I didn't do anything for this step
pip install pystan
```

Then under the `stan_env` environment, I opened my jupyter notebook, typed the following:
```
import pystan (it works)
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # now it doesn't work
```
It still gave me the same compiling error:
```
DistutilsExecError: command 'cl.exe' failed: No such file or directory

During handling of the above exception, another exception occurred:
CompileError: command 'cl.exe' failed: No such file or directory
```
The whole error message is long so I just pick the ones that seem significant.

Any thought?

**Comment by ahartikainen** [comment] 2017-09-10 08:03
Hi,

create `distutils.cfg` file under distutils folder (under Lib folder. To find your distutils path, open python in the correct env, import distutils and then print(distutils)) and add

    [build]
    compiler=mingw32

Currently you also need to edit pystan/model.py file and comment out two lines.

I will try to push the update next week so this will work without editing anything.

**Comment by lizzyhuang** [comment] 2017-09-10 16:09
Hi Ari,
I probably should have given you more details about the error. When I first got the error, it didn't come from the `_find_vcvarsall` function (my friend tried the same installation process and he did get error from that function. He changed the function a little bit and he was able to compile the model)

I got my first error from the `spawn.py` file, with the `_spawn_nt` function. The function says it's not able to find `cmd[0]`, i.e., it needs `cl.exe` files. So I added a new line in front of `executable = cmd[0]` as follows:
```
def _spawn_nt(cmd, search_path=1, verbose=0, dry_run=0):
    cmd[0] = r"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\cl.exe"
    executable = cmd[0]
    cmd = _nt_quote_args(cmd)
    if search_path:
        # either we find one or it stays the same
        executable = find_executable(executable) or executable
    log.info(' '.join([executable] + cmd[1:]))
    if not dry_run:
        # spawn for NT requires a full path to the .exe
        try:
            #print(os.P_WAIT, executable, cmd)
            rc = os.spawnv(os.P_WAIT, executable, cmd)
        except OSError as exc:
            # this seems to happen when the command isn't found
            if not DEBUG:
                cmd = executable
            raise DistutilsExecError(
                  "command %r failed: %s" % (cmd, exc.args[-1]))
        if rc != 0:
            # and this reflects the command running but failing
            if not DEBUG:
                cmd = executable
            raise DistutilsExecError(
                  "command %r failed with exit status %d" % (cmd, rc))
```
and reran it. So now the error has become the common "exit status 2" error that comes from `_msvccompiler.py` function
```
DistutilsExecError                        Traceback (most recent call last)
C:\Users\lizzy\Anaconda3\lib\distutils\_msvccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    381             try:
--> 382                 self.spawn(args)
    383             except DistutilsExecError as msg:

C:\Users\lizzy\Anaconda3\lib\distutils\_msvccompiler.py in spawn(self, cmd)
    500             os.environ['path'] = self._paths
--> 501             return super().spawn(cmd)
    502         finally:

C:\Users\lizzy\Anaconda3\lib\distutils\ccompiler.py in spawn(self, cmd)
    908     def spawn(self, cmd):
--> 909         spawn(cmd, dry_run=self.dry_run)
    910 

C:\Users\lizzy\Anaconda3\lib\distutils\spawn.py in spawn(cmd, search_path, verbose, dry_run)
     37     elif os.name == 'nt':
---> 38         _spawn_nt(cmd, search_path, dry_run=dry_run)
     39     else:

C:\Users\lizzy\Anaconda3\lib\distutils\spawn.py in _spawn_nt(cmd, search_path, verbose, dry_run)
     82             raise DistutilsExecError(
---> 83                   "command %r failed with exit status %d" % (cmd, rc))
     84 

DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64\\cl.exe' failed with exit status 2
```

So would you still suggest that I should create `distutils.cfg` and touch the `pystan/model.py` file?

**Comment by ahartikainen** [comment] 2017-09-10 19:09
Yes.

You should not touch `_spawn_nt` function. There is a way to get msvc 2017 to work. You have to import Extension from setuptools, not from distutils. If you want to use that, then edit the pystan/model.py to do that (don't comment out the other lines).

Please notice that msvc will not be supported compiler (it's broken with Eigen). Use gcc as specified in the other issue.

**Comment by lizzyhuang** [comment] 2017-09-10 19:38
Hi Ari,

I'm totally lost. So should I first remove the current `pystan` module, then reinstall following these steps?
```
# Optional - create a conda environment
conda create -n stan_env python=3.6
source activate stan_env

#dependencies
conda install numpy cython matplotlib scipy pandas

# gcc compiler components
conda install libpython
conda install -c msys2 m2w64-toolchain=5.3.0

# step with distutils.cfg
... (can we somehow automate this?)

# pip / conda
pip install pystan
```
But what's the `# step with distutils.cfg` you meant? Also, I searched online how to create a `cfg` file and got answers like using "notepad" and save it to ".cfg", is that what you mean?

I'm sorry, but I'm not a software developer and even I read all the referenced issues, I can hardly understand any of the jargon. It would be extremely helpful if anyone can summarize the entire process. Otherwise, I have to confirm again and again for very little issue. Thanks.

**Comment by ahartikainen** [comment] 2017-09-10 21:52
Hi, I understand your frustration. The current process is very complicated.

Everything else seems to be fine.

Now, the `cfg` step.

Open notepad / notepad++ (text editor).

Write these 2 lines:

[build]
compiler=mingw32

Save as - go and find the distutils package folder for stan_env. I assume that you have installed anaconda to some known place. Inside the Anaconda(/miniconda) folder there is an `envs` folder and inside it you can find `stan_env` folder. Inside that there is an Lib folder where you can find `distutils` folder. Save the file as `distutils.cfg`. It is just a normal text file.

Some possible problems.

1. You do not find Anaconda folder. Then it is probably inside a hidden `Appdata` folder. Go to your folder settings and enable the `show all folders`.
2. text file saves as `distutils.cfg.txt`. Your known extensions are hidden. Go to folder settings and enable (or unable) the setting to hide/show known file extensions.

After this go to pystan/model.py and comment out two lines (286-287)

    if platform.platform().startswith('Win'):
        extra_compile_args = ['/EHsc', '-DBOOST_DATE_TIME_NO_LIB']

to

    # if platform.platform().startswith('Win'):
    #    extra_compile_args = ['/EHsc', '-DBOOST_DATE_TIME_NO_LIB']

Now your pystan should use gcc and compile fine.

Now, next week I will create updared files so all of this should work without any file editing.

**Comment by lizzyhuang** [comment] 2017-09-11 01:50
Hi Ari,

Thank you so much for your patience. I redid the following steps:
```
#dependencies
conda install numpy cython matplotlib scipy pandas

# gcc compiler components
conda install libpython
conda install -c msys2 m2w64-toolchain=5.3.0
```
Then I went to my `Anaconda\Lib\distutils` folder and added the `distutils.cfg` file as you said.

Then `pip install pystan` (I did made sure I uninstalled `pystan` before I reinstalled the module). I didn't install all these in a new environment because I'm going to install `prophet` later, and `prophet` depends on `pystan` (and that's why I'm here). Let me know if installing everything in a separate environment would be a better option, and I can go ahead and do it.

I then ran the same 3 line example
```
import pystan #successful
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)
```
This time the error shows that `cygwinccompiler.py` isn't able to get `self.ld_version` as a number:
```
TypeError                       Traceback (most recent call last)
<ipython-input-3-15d1abb9774a> in <module>()
----> 1 model = pystan.StanModel(model_code=model_code)

C:\Users\lizzy\Anaconda3\lib\site-packages\pystan\model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args)
    309 
    310         try:
--> 311             build_extension.run()
    312         finally:
    313             if redirect_stderr:

C:\Users\lizzy\Anaconda3\lib\distutils\command\build_ext.py in run(self)
    306                                      verbose=self.verbose,
    307                                      dry_run=self.dry_run,
--> 308                                      force=self.force)
    309         customize_compiler(self.compiler)
    310         # If we are cross-compiling, init the compiler now (if we are not

C:\Users\lizzy\Anaconda3\lib\distutils\ccompiler.py in new_compiler(plat, compiler, verbose, dry_run, force)
   1029     # with classes that expect verbose to be the first positional
   1030     # argument.
-> 1031     return klass(None, dry_run, force)
   1032 
   1033 

C:\Users\lizzy\Anaconda3\lib\distutils\cygwinccompiler.py in __init__(self, verbose, dry_run, force)
    280     def __init__(self, verbose=0, dry_run=0, force=0):
    281 
--> 282         CygwinCCompiler.__init__ (self, verbose, dry_run, force)
    283 
    284         # ld_version >= "2.13" support -shared so use it instead of

C:\Users\lizzy\Anaconda3\lib\distutils\cygwinccompiler.py in __init__(self, verbose, dry_run, force)
    124         # same as the rest of binutils ( also ld )
    125         # dllwrap 2.10.90 is buggy
--> 126         if self.ld_version >= "2.10.90":
    127             self.linker_dll = "gcc"
    128         else:

TypeError: '>=' not supported between instances of 'NoneType' and 'str'
```
Is there anything that you think I should check? I did download a cygwin-terminal so that I could bash on Windows. That was a month ago for some other projects. I don't know whether my previous experience with cygwin may have anything to do with this. Thanks.

**Comment by ahartikainen** [comment] 2017-09-11 04:42
Please and try to run pystan from cmd. I have no experience with cygwin.

**Comment by lizzyhuang** [comment] 2017-09-11 13:36
No, I did do all the above through cmd, and got the error from ``cygwinccompiler.py`

I mentioned cygwin because the error seems related to cygwin. I don't know whether that has anything to do with the fact that I installed cygwin terminal a month ago and that might mess up some of my computer's setting (and I also don't know too much about cygwin). Sorry if I previous reply has caused any confusion.

**Comment by lizzyhuang** [comment] 2017-09-13 17:16
Hi Ari,

I have removed the entire Cygwin64 folder in my computer, as well as the Cygwin64 terminal. I reran the example but still get the same error message from `cygwinccompiler.py` saying that 
```
C:\Users\lizzy\Anaconda3\lib\distutils\cygwinccompiler.py in __init__(self, verbose, dry_run, force)
    124         # same as the rest of binutils ( also ld )
    125         # dllwrap 2.10.90 is buggy
--> 126         if self.ld_version >= "2.10.90":
    127             self.linker_dll = "gcc"
    128         else:

TypeError: '>=' not supported between instances of 'NoneType' and 'str'
```
Any thought about that? Thanks.

**Comment by lizzyhuang** [comment] 2017-09-13 21:18
Hi Ari,

Sorry to bug you, but I think I have found the cause of the error. Since `cygwinccompiler.py` keeps complaining that `get_versions()` function cannot extract any `self.ld_version` and `self.gcc_version` (they're both NoneType and therefore, they can't walk through the `if` statements and raise the TypeError when I compiled the model). So what I did was, I changed all the `if self.ld_version >= some string` statements in `cygwinccompiler.py` into `if self.ld_version != None and if self.ld_version >= some string`. Of course this would not actually help, but it helped me to see what `cygwinccompiler.py` would give me.

So the answer was, my `msc_version` is 1900 but inside my `cygwinccompiler.py`, there's no such thing saying `elif msc_version >= 1900` clause. I googled this and compared this with my friend's `cygwinccompiler.py` file. My friend told me that he does have the clause for `msc_version >= 1900` and therefore he could compile the model (he only had problem with `vcvarsall.bat x64`, and he manually added a route to find it). Since `cygwinccompiler.py` belongs to Anaconda, but not PyStan, so we suspected the reason was because my Anaconda version was too low......

My Anaconda version was 4.3.1, but now Anaconda has upgraded to 4.4.0 (my friend uses this version)

So my approach to solve the problem:
1. Upgrade Anaconda by using
```
conda upgrade --all
```
2. Uninstall `PyStan` (I tried and it seems if I installed `PyStan` under the older version of Anaconda, even I have upgraded Anaconda, it still went through the `cygwinccompiler.py`)

3. I opened `Anaconda prompt` and do `pip install pystan`.

4. I created the `distutils.cfg` file as you suggested
```
[build]
compiler = mingw32
```
5. I commented out `pystan/model.py` the 2 lines (286-287) you suggested

6. Finally I opened Jupyter Notebook and tried the example:
```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # with luck the result will be near 0
```
And now it runs.......

I hope my post will be helpful. Since many people may not realize it's their Anaconda version that causes this trouble. Also, it really surprised me when inside `cygwinccompiler.py`, the `get_versions()` function was not at all working. That's why I kept getting NoneType for `self.ld_version` and `self.gcc_version`. Even though with the latest Anaconda combined with PyStan, running the example model should not need to go through `cygwinccompiler.py`, but I think it may be an interesting phenomenon to you guys when next time you need to improve any function of PyStan that may trigger this part of `cygwinccompiler.py`.

**Comment by ahartikainen** [comment] 2017-09-13 21:24
Ok, that problem was caused by the `msvc` compiler. Distutils is not yet updated for MSVC 2017.

Great that you got it working.

I have create a new PR to update the Windows support. After the next release this should work without any manual editing. (only setuptools needs to be upgraded (`pip install setuptools -U`).

**Comment by lizzyhuang** [comment] 2017-09-14 00:58
Hi Ari,

I've found something new here. Probably it will help when you update the Windows support. To summarize:

1.it seems that the Visual Studio C++ Build Tool 2015 isn't giving the correct path for `cl.exe`, which causes the problem. 
2. If under only Visual Studio 2017 without VS C++ Build Tool 2015 (just like my friend's situation), `_msvccompiler.py` is not able to find the right path for `vcvarsall.bat` and `vcruntime.dll`. 

This is how I figure the above out:

Previously I mentioned that my Visual Studio is 2017 version. But I also installed the Visual Studio C++ Build Tool 2015. And it turns out that this is the problem.

I did get `PyStan` and `FBprophet` working successfully, but I wasn't able to install `PyFlux`. When I installed `PyFlux`, since I created the `distutils.cfg` file which points the compiler to `mingw32`, `PyFlux` got into the `mingw32compiler.py` file and raised a `UnicodeDecodeError`. So I had to go back to the origin and tried to figure out whether I could do something else so that I didn't have to create the `distutils.cfg` file and comment out the 2 lines in `model.py`.

When the first error inside `spawn.py` came, it also combined with an error from `_msvccompiler.py`. I believe the problem comes from the fact that `_msvccompiler.py` gave wrong `vcvarsall.dat` and `vcruntime.dll` paths to `spawn` and that's why `spawn.py` was not able to extract the path for `cmd[0]` (it showed as `cl.exe`, not a path for `cl.exe`).

I printed out the paths for `vcvarsall` and `vcruntime` and found out that they came from the `Microsoft Visual Studio\2017\Shared\14` folder, instead of the usual `Microsoft Visual Studio\2017\community` that I have. The `community` folder comes from VS 2017, but the `shared\14` folder comes from the Visual Studio C++ Build Tool 2015.

Finally, I changed the `_find_vcvarsall` function in `_msvccompiler.py`, manually set direct paths for `vcvarsall` and `vcruntime` (both from `2017\community`, not the `shared\14` folder). Then everything is fine now. I can install `fbprophet` without any problem, as well as `PyFlux`. And I don't need to worry about that other packages may not like the compiler to be `mingw32`.

**Comment by vickyting0910** [comment] 2018-01-07 15:24
Thanks for the above posts, esp. @lizzyhuang. This post is just for the future reference. 

Finally, got the sample codes work by compiling from the source code. 

My machine is on Windows 7, x64 with Anaconda3 installed. 
1. Install Visual Studio 2017 & Visual Studio C++ Build Tool 2015 at http://landinghub.visualstudio.com/visual-cpp-build-tools

2. Update Conda
conda update conda
conda update --all

3. Recheck the dependencies
pip install setuptool
conda install numpy cython matplotlib scipy pandas

4. Install gcc compiler components
conda install libpython
conda install -c msys2 m2w64-toolchain=5.3.0

5. created distutils.cfg file inside Anaconda3\Lib\distutils folder with the following:
[build]
compiler = mingw32

6. Git at https://git-scm.com/downloads
git clone --recursive https://github.com/stan-dev/pystan.git

7. Compile from the source code
python setup.py build --compiler=mingw32
python setup.py install

**Comment by windmac** [comment] 2019-01-04 08:55
I've just solved this problem a minute ago by following this instruction to install gcc 64 to my computer:
https://wiki.python.org/moin/WindowsCompilers
Finally it works, hope it can help :)

**Comment by Nathan-Furnal** [comment] 2019-01-05 16:45
Just wanted to say that on Python 3.7, windows 10 @vickyting0910 solution worked for me while the other solutions didn't.

Thanks a lot @vickyting0910 !

**Comment by ahartikainen** [comment] 2019-01-05 16:56
On Windows the first step is not needed. (MSVC)

Following the instructions in docs works. `pip install pystan` just takes a "long time".

So you need only

mingw-w64 + libpython
numpy cython (matplotlib, scipy, pandas)
and then `pip install pystan`

Remember to run these commands from cmd.exe (anaconda prompt is recommended)

**Comment by Nathan-Furnal** [comment] 2019-01-05 16:58
For some reason it didn't work for me in the beginning, I got a similar issue as @lizzyhuang then after some re-installing the environment, it did work. I don't kow why.

**Comment by vickyting0910** [comment] 2019-10-09 21:17
Updated: 
Now, only one line of code works for Python 3.7, windows 10.
conda install pystan
