### ISSUE TITLE
Error printing infinity in model fit summary

### ISSUE THREAD

**Issue by danielrosenbloom** [stan-dev/pystan#249] opened 2016-08-10 18:55 UTC
#### Summary:

If a statistic to be printed in the summary is infinite or NaN, an error is thrown.
#### Description:

After I successfully run `fit = model.sampling(...)`, I try to do a `print fit` to get the summary. Instead of printing the summary, I get the error:

```
File "/Users/dsr2131/VIRTUALENVS/211/lib/python2.7/site-packages/pystan/misc.py", line 83, in _print_stanfit
    s['summary_colnames'], digits_summary)
  File "/Users/dsr2131/VIRTUALENVS/211/lib/python2.7/site-packages/pystan/misc.py", line 112, in _array_to_table
    line += '{num:>{width}}'.format(num=_format_number(num, n_digits, max_col_width - 1), width=width)
  File "/Users/dsr2131/VIRTUALENVS/211/lib/python2.7/site-packages/pystan/misc.py", line 151, in _format_number
    return str(int(round(num)))
OverflowError: cannot convert float infinity to integer
```

This usually pops up in a model where the Rhat is undefined for a parameter; I can easily fix it by replacing line 151 in misc.py (`return str(int(round(num)))`) with:

`try:
    return str(int(round(num)))
except OverflowError:
    return str(round(num))`
#### PyStan Version:

Error in both 2.9 and 2.11
#### Python Version:

2.7
#### Operating System:

OSX 10.10

**Comment by ahartikainen** [comment] 2016-10-21 08:42
Line 142 should grab `nan`s. Have you had any problems with `nan` or only with `inf`?
    
    # line 142
    if math.isnan(num):
        return str(num)

Maybe cleaner solution is to add `math.isinf(num)` for if statement or create new if statement for `inf`. This grabs both negative and positive infinities.

    # line 142
    if math.isnan(num) or math.isinf(num):
        return str(num)

    # or
    if math.isinf(num):
        return str(num)

**Comment by ariddell** [comment] 2016-10-23 19:46
Thanks @ahartikainen . This is helpful. I'll try to fix this for the next release.

**Comment by scfrank** [comment] 2017-01-18 18:37
Unfortunately I still get the OverflowError that @danielrosenbloom reported, with the new code.  The fix suggested above by @ahartikainen worked. 

Specifically, this changes _format_number on line 144, not _format_number_si as in the commit (though the change in the commit is probably a good idea too).

**Comment by ariddell** [comment] 2017-01-18 21:37
Are you still getting an error under v2.14.0.0?

**Comment by scfrank** [comment] 2017-01-18 21:40
Yes, that's the version I have installed (as reported by
pystan.__version__).

**Comment by ariddell** [comment] 2017-01-18 21:43
Got it. This needs to be fixed. Thanks for pinpointing the needed change (line #144 )

**Comment by erinshellman** [comment] 2017-03-21 17:51
Hey, 

Any updates on a fix for this? I'm getting the same thing on Ubuntu 16.04. I'm able to fit successfully fit the model, but am unable to print the results:

```{python}
print fit
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-12-60318b13f8b2> in <module>()
----> 1 print fit

stanfit4anon_model_459b43b455ed6252b68a20092e56bb17_2349123205138917991.pyx in stanfit4anon_model_459b43b455ed6252b68a20092e56bb17_2349123205138917991.StanFit4Model.__str__ (/tmp/tmpGK07Gk/stanfit4anon_model_459b43b455ed6252b68a20092e56bb17_2349123205138917991.cpp:12288)()

/usr/local/lib/python2.7/dist-packages/pystan/misc.pyc in _print_stanfit(fit, pars, probs, digits_summary)
     81         s = _summary(fit, pars, probs)
     82         body = _array_to_table(s['summary'], s['summary_rownames'],
---> 83                                s['summary_colnames'], digits_summary)
     84         return header + body + footer
     85 

/usr/local/lib/python2.7/dist-packages/pystan/misc.pyc in _array_to_table(arr, rownames, colnames, n_digits)
    110             if colnames[j] == 'n_eff':
    111                 num = int(round(num, 0))
--> 112             line += '{num:>{width}}'.format(num=_format_number(num, n_digits, max_col_width - 1), width=width)
    113         lines.append(line)
    114     return '\n'.join(lines)

/usr/local/lib/python2.7/dist-packages/pystan/misc.pyc in _format_number(num, n_signif_figures, max_width)
    151         if n_digits(num) >= n_signif_figures:
    152             # the int() is necessary for consistency between Python 2 and 3
--> 153             return str(int(round(num)))
    154         else:
    155             return str(num)

OverflowError: cannot convert float infinity to integer
```

**Comment by ahartikainen** [comment] 2017-03-21 18:50
Is the error coming from `int(num)==inf` due to python 2.7? Some cornercase where calling `int` with big number creates `inf`?

**Comment by erinshellman** [comment] 2017-03-21 20:00
I think so? Says this is in the trace above: `# the int() is necessary for consistency between Python 2 and 3`. I confirmed that I'm able to produce results in `rstan`. I get some warnings about the quality of fit, but am still able to view the model output in R.

**Comment by ahartikainen** [comment] 2017-03-21 20:08
Ok, I was wrong. It is still missing the `math.isinf(num)` test in 2.14 (.whl file from pypi).

So this will be corrected in version 2.15.

Before that you can always install the latest version from github.

    pip install git+https://github.com/stan-dev/pystan

or 
  
    git clone --recursive https://github.com/stan-dev/pystan
    cd pystan
    python setup.py install

**Comment by erinshellman** [comment] 2017-03-21 20:44
Just updated to the development version and unfortunately getting new errors:

```{python}
[2017-03-21 20:42:02,106] {model.py:227} INFO - COMPILING THE C++ CODE FOR MODEL anon_model_52f51f59350a9b6a64738d6d1554e4ad NOW.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-67fc2a89f998> in <module>()
----> 1 fit = pystan.stan(model_code=model, data=norm_input)

/home/shellman/projects/zwork/venv/local/lib/python2.7/site-packages/pystan/api.pyc in stan(file, model_name, model_code, fit, data, pars, chains, iter, warmup, thin, init, seed, algorithm, control, sample_file, diagnostic_file, verbose, boost_lib, eigen_lib, n_jobs, **kwargs)
    393                      sample_file=sample_file, diagnostic_file=diagnostic_file,
    394                      verbose=verbose, algorithm=algorithm, control=control,
--> 395                      n_jobs=n_jobs, **kwargs)
    396     return fit

/home/shellman/projects/zwork/venv/local/lib/python2.7/site-packages/pystan/model.pyc in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)
    717         call_sampler_args = izip(itertools.repeat(data), args_list, itertools.repeat(pars))
    718         call_sampler_star = self.module._call_sampler_star
--> 719         ret_and_samples = _map_parallel(call_sampler_star, call_sampler_args, n_jobs)
    720         samples = [smpl for _, smpl in ret_and_samples]
    721 

/home/shellman/projects/zwork/venv/local/lib/python2.7/site-packages/pystan/model.pyc in _map_parallel(function, args, n_jobs)
     77         if n_jobs == -1:
     78             n_jobs = None
---> 79         with multiprocessing.Pool(processes=n_jobs) as pool:
     80             map_result = pool.map(function, args)
     81     else:

AttributeError: __exit__
```

**Comment by ahartikainen** [comment] 2017-03-21 20:52
Ok, that is an error with `with multiprocessing.Pool...`. This will not work in python 2.7.

http://stackoverflow.com/questions/25968518/python-multiprocessing-lib-error-attributeerror-exit

If you want. You can manually change `model.py` file on those lines to

    try:
        pool = multiprocessing.Pool(processes=n_jobs)
        map_result = pool.map(function, args)
    finally:
        pool.close()
        pool.join()

**Comment by ariddell** [comment] 2017-04-20 22:40
I think this is fixed. If not, I'll make a 2.15.1 release.

**Closed by ariddell** 2017-04-20 22:40 UTC
