### ISSUE TITLE
Permit running zero iterations of the sampler in StanModel.sampling?

### ISSUE THREAD

**Issue by axch** [stan-dev/pystan#199] opened 2015-12-14 22:32 UTC
Please forgive me if this a Stan noob request.

I would like to be able to programmatically use various parts of a Stan model.  For example, I would like to sample generated quantities given specific values of the parameters, without having HMC move them.  The simplest way to do that in the pystan API seems to be to just run zero iterations of the sampler, but when I try that I trip over the following check in pystan/misc.py, lines 374-376:
```
    iter = int(iter)
    if iter < 1:
        raise ValueError("`iter` should be a positive integer.")
```
Is there a reason why that bound is one rather than zero?  Is there some other way to accomplish what I am trying to accomplish?  I am using pystan v2.8.0, and would prefer to stay within pystan if possible (but could consider moving to some other interface if that makes more sense).

Thanks!

**Comment by ariddell** [comment] 2015-12-14 22:48
This is a known bug and will be fixed in PyStan 3.

**Comment by bob-carpenter** [comment] 2015-12-14 23:53
We're also planning to allow generated quantities to be
run independently given values, but it'll be a while before
that happens.

- Bob

**Comment by axch** [comment] 2015-12-15 18:16
OK.  Then I will live with `iter=1` for the time being.

**Comment by axch** [comment] 2015-12-16 13:12
Workaround for problems with known scale: Run one step of non-adaptive HMC with a relatively tiny step size and trajectory length:
```
control = {'adapt_engaged': False, 'stepsize': 1e-12, 'int_time': 1e-12, 'stepsize_jitter': 0}
model.sampling(iter=1, chains=1, algorithm="HMC", control=control)
```
The parameters still move, but by amounts on the order of 1e-12, which is acceptable when the scale of the problem's geometry is near unity.  Oddly, when I set the step size and trajectory length to exactly zero, Stan seems to ignore the setting and moves the parameters by a substantial amount (presumably falls back to default?).

It would still be nice to get exactly zero movement, or the "Fixed_param" algorithm (Issue #200), though, because those are scale-invariant.

**Comment by ariddell** [comment] 2016-01-13 14:32
This will be fixed by design in (Py)Stan 3. It's a wontfix for PyStan 2.

**Closed by ariddell** 2016-01-13 14:32 UTC
Labels: bug
